project_id = "cgcgvhgrvmuwntdxmemw"

[functions.ai-suggest-offerings]
enabled = true
verify_jwt = true

[functions.send-approval-email]
enabled = true
verify_jwt = true

[functions.get-signed-url]
enabled = true
verify_jwt = false